version: "3.8"
networks:
  mongodb-network:
    name: mongodb-network
services:
  mongodb1:
    image: mongo:5
    container_name: mongodb1
    command: ["--replSet", "replicaname", "--bind_ip_all", "--port", "27018"]
    volumes:
      - ./data/mongodb1:/data/db
    ports:
      - 27018:27018
    networks:
      - mongodb-network
    healthcheck:
      test: test $$(echo "rs.initiate({_id:'replicaname',members:[{_id:0,host:\"mongodb1:27018\"},{_id:1,host:\"mongodb2:27019\"},{_id:2,host:\"mongodb3:27020\"}]}).ok || rs.status().ok" | mongo --port 27018 --quiet) -eq 1
      interval: 10s
      start_period: 30s

  mongodb2:
    image: mongo:5
    container_name: mongodb2
    command: ["--replSet", "replicaname", "--bind_ip_all", "--port", "27019"]
    volumes:
      - ./data/mongodb2:/data/db
    ports:
      - 27019:27019
    networks:
      - mongodb-network

  mongodb3:
    image: mongo:5
    container_name: mongodb3
    command: ["--replSet", "replicaname", "--bind_ip_all", "--port", "27020"]
    volumes:
      - ./data/mongodb3:/data/db
    ports:
      - 27020:27020
    networks:
      - mongodb-network